name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
        


    - name: Make Gradle Wrapper executable
      run: chmod +x ./gradlew

    - name: Build acceptance tests
      run: ./gradlew acceptance:build

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
        


    - name: Make Gradle Wrapper executable
      run: chmod +x ./gradlew

    - name: Run Acceptance Tests
      run: ./gradlew acceptance:build
    - uses: ashley-taylor/junit-report-annotations-action@master
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: 'acceptance/test-results/test/*.xml'
        if: always()

    # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
